import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import { Toaster } from 'sonner';

const quicksand = Quicksand({
    subsets: ["latin"],
    weight: ["400", "500", "600"],
    variable: "--font-quicksand",
});

import "./globals.scss";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import './theme.scss';

import RootWrapper from "@/components/layouts/RootWrapper";
import BootstrapClient from "@/components/layouts/BootstrapClient";
import {DataContextProvider} from "@/lib/dataContext";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <head>
            <link rel="icon" href="/favicon.ico" sizes="any" />
        </head>
        <body className={quicksand.className}>
            <BootstrapClient/>
            <Toaster position="top-right" expand={true} richColors closeButton/>
            <DataContextProvider>
                <RootWrapper>
                    {children}
                </RootWrapper>
            </DataContextProvider>
        </body>
        </html>
    );
}