export const dynamic = 'force-dynamic';

import type { Metadata } from "next";
import { Quicksand, Inter } from "next/font/google";

const quicksand = Quicksand({
    subsets: ["latin"],
    weight: ["400", "500", "600"],
    variable: "--font-quicksand",
});

import "./globals.scss";

import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';

import RootWrapper from "@/components/layouts/RootWrapper";
import BootstrapClient from "@/components/layouts/BootstrapClient";

import './theme.scss'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <head>
            <link rel="icon" href="/favicon.ico" sizes="any" />
        </head>
        <body className={quicksand.className}>
        <BootstrapClient/>
        <RootWrapper>{children}</RootWrapper>
        </body>
        </html>
    );
}
